### ISSUE TITLE
All Markets

### ISSUE THREAD

**Issue by flfsbr** [sean1000444/Bittrex-Arbitrage-Discovery#1]
Hi, is it possible to enable all markets?

**Comment by siobh9** [comment]
Wow, I am sorry that I took so long to respond! It would be, and you can: all you need to do is input all of the ETH pairs into current_list and the program will cycle through them all. I tried using getTotalMarkets, but that list in Bittrex is an ordered one and thus changes with the fluctuating prices of the currencies each time you access it, making indexing for a loop unpredictable. But if you would like to compile them all into a [" ", " "] list I would be happy to push that change to this code.

**Comment by siobh9** [comment]
If you'd just like to put the list here should you choose to make it, that would work great.
